### ISSUE TITLE
Configurar lenguaje de la página

### ISSUE THREAD

**Issue by juancuiule** [pdep-lunes/bitacora#12]
Aparece una sugerencia de traducción del inglés al español que no es necesaria... probablemente tiene algo que ver con meta tags mal setteados.

![image](https://user-images.githubusercontent.com/12143451/54952696-5762fc80-4f25-11e9-97fe-492111aead9c.png)

**Comment by mnmallea** [comment]
![image](https://user-images.githubusercontent.com/28768483/55101006-e39a2e80-50a1-11e9-9b7a-fcfc1a9d1ada.png)

**Comment by juancuiule** [comment]
#13
